2019-04-16 11:40:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "PEOPLE" not found; SQL statement:
insert into people (name,counter) values (?, ?) [42102-197]
2019-04-16 11:40:12 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:/home/coder/IdeaProjects/greet-in-java/target/greet_java.mv.db [1.4.197/7]" [50000-197]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:307)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:95)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2506)
	at org.h2.mvstore.MVStore.panic(MVStore.java:383)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:364)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2934)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:155)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:100)
	at org.h2.engine.Database.getPageStore(Database.java:2538)
	at org.h2.engine.Database.open(Database.java:709)
	at org.h2.engine.Database.openDatabase(Database.java:286)
	at org.h2.engine.Database.<init>(Database.java:280)
	at org.h2.engine.Engine.openSession(Engine.java:66)
	at org.h2.engine.Engine.openSession(Engine.java:179)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
	at org.h2.engine.Engine.createSession(Engine.java:140)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:433)
	at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnection(DriverDataSource.java:399)
	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:56)
	at org.flywaydb.core.internal.database.DatabaseFactory.createDatabase(DatabaseFactory.java:72)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1670)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:1356)
	at org.flywaydb.maven.MigrateMojo.doExecute(MigrateMojo.java:35)
	at org.flywaydb.maven.AbstractFlywayMojo.execute(AbstractFlywayMojo.java:746)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:955)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:290)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:194)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: The file is locked: nio:/home/coder/IdeaProjects/greet-in-java/target/greet_java.mv.db [1.4.197/7]" [50000-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 52 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/home/coder/IdeaProjects/greet-in-java/target/greet_java.mv.db [1.4.197/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:870)
	at org.h2.mvstore.FileStore.open(FileStore.java:173)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:350)
	... 46 more
2019-04-16 11:41:06 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Parameter "#2" is not set; SQL statement:
insert into people (name,counter) values (?, ?) [90012-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.Parameter.checkSet(Parameter.java:81)
	at org.h2.command.Prepared.checkParameters(Prepared.java:170)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:261)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:249)
	at net.greet.GreetWithDatabase.namesWithDefault(GreetWithDatabase.java:80)
	at net.greet.GreeterWIthDB.main(GreeterWIthDB.java:24)
2019-04-16 11:42:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Parameter "#2" is not set; SQL statement:
insert into people (name,counter) values (?, ?) [90012-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.Parameter.checkSet(Parameter.java:81)
	at org.h2.command.Prepared.checkParameters(Prepared.java:170)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:261)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:249)
	at net.greet.GreetWithDatabase.namesWithDefault(GreetWithDatabase.java:80)
	at net.greet.GreeterWIthDB.main(GreeterWIthDB.java:24)
2019-04-16 11:43:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Invalid value "2" for parameter "parameterIndex" [90008-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:240)
	at org.h2.jdbc.JdbcPreparedStatement.setParameter(JdbcPreparedStatement.java:1560)
	at org.h2.jdbc.JdbcPreparedStatement.setInt(JdbcPreparedStatement.java:406)
	at net.greet.GreetWithDatabase.namesWithDefault(GreetWithDatabase.java:85)
	at net.greet.GreeterWIthDB.main(GreeterWIthDB.java:24)
2019-04-16 11:44:50 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "AYA"; SQL statement:
update people set counter = ? where name = ? [22018-197]
2019-04-16 11:51:12 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "AYA"; SQL statement:
update people set counter = ? where name = ? [22018-197]
2019-04-16 11:59:45 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "AYA"; SQL statement:
update people set counter = ? where name = ? [22018-197]
2019-04-16 12:18:30 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Invalid value "2" for parameter "parameterIndex" [90008-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:240)
	at org.h2.jdbc.JdbcPreparedStatement.setParameter(JdbcPreparedStatement.java:1560)
	at org.h2.jdbc.JdbcPreparedStatement.setInt(JdbcPreparedStatement.java:406)
	at net.greet.GreetWithDatabase.namesWithDefault(GreetWithDatabase.java:84)
	at net.greet.GreeterWIthDB.main(GreeterWIthDB.java:23)
2019-04-16 12:26:56 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "aya"; SQL statement:
update people set counter = ? where name = ? [22018-197]
2019-04-16 12:59:34 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "name" not found [42122-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3174)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3247)
	at org.h2.jdbc.JdbcResultSet.getString(JdbcResultSet.java:310)
	at net.greet.GreetWithDatabase.namesWithLang(GreetWithDatabase.java:109)
	at net.greet.GreeterWIthDB.main(GreeterWIthDB.java:26)
2019-04-16 13:00:34 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "name" not found [42122-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3174)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3247)
	at org.h2.jdbc.JdbcResultSet.getString(JdbcResultSet.java:310)
	at net.greet.GreetWithDatabase.namesWithLang(GreetWithDatabase.java:109)
	at net.greet.GreeterWIthDB.main(GreeterWIthDB.java:26)
2019-04-16 14:58:22 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "aya"; SQL statement:
update people set counter = ? where name = ? [22018-197]
2019-04-16 15:07:18 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "name" not found [42122-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3174)
	at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3247)
	at org.h2.jdbc.JdbcResultSet.getString(JdbcResultSet.java:310)
	at net.greet.GreetWithDatabase.namesWithLang(GreetWithDatabase.java:109)
	at net.greet.GreeterWIthDB.main(GreeterWIthDB.java:26)
2019-04-16 15:19:12 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "aya"; SQL statement:
update people set counter = ? where name = ? [22018-197]
2019-04-16 15:34:41 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "aya"; SQL statement:
update people set counter = ? where name = ? [22018-197]
